language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

env:
  global:
    - DB_NAME="zfcuserforgotpassword"
    - DB_USER="travis"

before_script:
 - mysql -uroot -e "CREATE DATABASE $DB_NAME;" || aborterror "Unable to create database."
 - mysql -uroot $DB_NAME < data/reset.sql || aborterror "Unable to import table."
 - mysql -uroot $DB_NAME < test/user.sql || aborterror "Unable to import table."
 - mysql -uroot -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';"
 - composer install

notifications:
  email: false
